name: Capture Django App Screenshot

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: docker build -t local .
    - run: docker run --name demo -d -p 8000:8000 local
    - run: sleep 10

    - name: screenshot
      uses: saadmk11/comment-website-screenshot@main
      with:
        upload_to: github_branch
        capture_changed_html_files: yes
        capture_urls: 'http://172.17.0.1:8000/, http://172.17.0.1:8000/admin/login/'
